/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import TextProcess.*;
import static TextProcess.TextFilePreProcess.newSubject;
import edu.mit.jwi.IDictionary;
import edu.mit.jwi.IRAMDictionary;
import edu.stanford.nlp.trees.Tree;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author anter_000
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evalForAllSubjLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        subjectLabel = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        evalForOneSubjTextArea = new javax.swing.JTextArea();
        getSentimentButton = new javax.swing.JButton();
        outputIntoCSVButton = new javax.swing.JButton();
        outputIntoTextButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chooseFileBtn = new javax.swing.JButton();
        teacherNameText = new javax.swing.JTextField();
        teacherNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        evalForAllSubjTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        filenameTextField = new javax.swing.JTextField();
        openMulitpleFileAnalysisWindow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        positiveScoreTextField = new javax.swing.JTextField();
        negativeScoreTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        positiveStatementsTextArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        negativeStatementsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        evalForAllSubjLabel.setText(" ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sentiment Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        subjectLabel.setText("Subject:");

        subjectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Evaluation for ______________");

        evalForOneSubjTextArea.setEditable(false);
        evalForOneSubjTextArea.setColumns(20);
        evalForOneSubjTextArea.setLineWrap(true);
        evalForOneSubjTextArea.setRows(5);
        evalForOneSubjTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(evalForOneSubjTextArea);

        getSentimentButton.setText("Get Sentiment");
        getSentimentButton.setEnabled(false);
        getSentimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSentimentButtonActionPerformed(evt);
            }
        });

        outputIntoCSVButton.setText("Output into csv file");
        outputIntoCSVButton.setName("outputSentenceButton"); // NOI18N
        outputIntoCSVButton.setVisible(false);
        outputIntoCSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputSentencesButtonActionPerformed(evt);
            }
        });

        outputIntoTextButton.setText("Output into text file");
        outputIntoTextButton.setVisible(false);
        outputIntoTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputIntoTextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subjectLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(getSentimentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputIntoCSVButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputIntoTextButton)))
                        .addGap(0, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getSentimentButton)
                    .addComponent(outputIntoCSVButton)
                    .addComponent(outputIntoTextButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Evaluation Content", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        chooseFileBtn.setText("Input File");
        chooseFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileBtnActionPerformed(evt);
            }
        });

        teacherNameText.setEditable(false);

        teacherNameLabel.setText("Teacher Name:");

        jLabel3.setText("Entire Evaluation:");

        evalForAllSubjTextArea.setEditable(false);
        evalForAllSubjTextArea.setColumns(20);
        evalForAllSubjTextArea.setLineWrap(true);
        evalForAllSubjTextArea.setRows(5);
        evalForAllSubjTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(evalForAllSubjTextArea);

        jLabel2.setText("Filename:");

        openMulitpleFileAnalysisWindow.setText("Open Multiple File Analysis");
        //openMulitpleFileAnalysisWindow.setVisible(false);
        openMulitpleFileAnalysisWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMulitpleFileAnalysisWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(teacherNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(0, 0, 0))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(filenameTextField)
                                .addGap(0, 0, 0))
                            .addComponent(teacherNameText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 350, Short.MAX_VALUE)
                        .addComponent(openMulitpleFileAnalysisWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseFileBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFileBtn)
                    .addComponent(openMulitpleFileAnalysisWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sentiment Analysis Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel4.setText("Positive Score:");

        jLabel6.setText("Negative Score:");

        jLabel7.setText("List of Positive statements");

        jLabel8.setText("List of negative statements");

        positiveStatementsTextArea.setColumns(20);
        positiveStatementsTextArea.setRows(5);
        jScrollPane3.setViewportView(positiveStatementsTextArea);

        negativeStatementsTextArea.setColumns(20);
        negativeStatementsTextArea.setRows(5);
        jScrollPane7.setViewportView(negativeStatementsTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positiveScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(negativeScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addContainerGap())
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(positiveScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(negativeScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evalForAllSubjLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(evalForAllSubjLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputSentencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputSentencesButtonActionPerformed
        // TODO add your handling code here:
        try{
            TextFilePreProcess.outputSentencesCSV(evalForOneSubjTextArea.getText());
        }
        catch(FileNotFoundException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_outputSentencesButtonActionPerformed

    private void outputIntoTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputIntoTextButtonActionPerformed
        // TODO add your handling code here:
        try{
            TextFilePreProcess.outputSentencesText(evalForOneSubjTextArea.getText());
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_outputIntoTextButtonActionPerformed

    private void openMulitpleFileAnalysisWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMulitpleFileAnalysisWindowActionPerformed
        // TODO add your handling code here:
        new OpenMultipleFiles().setVisible(true);
    }//GEN-LAST:event_openMulitpleFileAnalysisWindowActionPerformed

    private void getSentimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSentimentButtonActionPerformed
        // TODO add your handling code here:
        
        String text = TextFilePreProcess.cleanTextFromEvaluation(evalForOneSubjTextArea.getText());
        
        //new ProgressDialogue().setVisible(true);
        
        String score = SummarizeText.getSentimentofOneDocument(text);
        
        String[] posNegScore = score.split(",");
        
        positiveScoreTextField.setText(posNegScore[0]);
        negativeScoreTextField.setText(posNegScore[1]);
        
        List<String> positiveList = SummarizeText.getPositiveSentences();
        List<String> negativeList = SummarizeText.getNegativeSentences();
        
        positiveStatementsTextArea.setText("");
        for(String statement : positiveList){
            positiveStatementsTextArea.append("> " + statement + "\n");
        }
        positiveStatementsTextArea.setCaretPosition(0);
        
        negativeStatementsTextArea.setText("");
        for(String statement : negativeList){
            negativeStatementsTextArea.append("> " + statement + "\n");
        }
        negativeStatementsTextArea.setCaretPosition(0);
        
        write("sentiment analysis complete");
    }//GEN-LAST:event_getSentimentButtonActionPerformed

    private void subjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboBoxActionPerformed
        // TODO add your handling code here:
        if(!teacherNameText.getText().isEmpty() && subjectComboBox.getItemCount() != 0){
            String subjectEval = TextFilePreProcess.getSubjectEvaluation(evalForAllSubjTextArea.getText(), subjectComboBox.getSelectedItem().toString());
            evalForOneSubjTextArea.setText("");
            evalForOneSubjTextArea.setText(subjectEval);
            evalForOneSubjTextArea.setCaretPosition(0);
            jLabel5.setText("Evaluation for " + subjectComboBox.getSelectedItem().toString());
        }
        getSentimentButton.setEnabled(true);
    }//GEN-LAST:event_subjectComboBoxActionPerformed

    private void chooseFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser;
        fileChooser = new JFileChooser(new File("C:\\Users\\user\\Google Drive\\Current Thesis\\Resources\\Text Files"));
        int returnVal = fileChooser.showOpenDialog(fileChooser.getParent());
        String cleanedText = "";

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            //This is where a real application would open the file.
            System.out.print("Opening: " + file.getName() + "." + "\n");
            System.out.print("" + file.getAbsolutePath() + "" + "\n");

            evalForAllSubjTextArea.setText(""); //Empty text field

            //Fill with first clean up of text
            cleanedText += TextFilePreProcess.getImportantText(file);
            evalForAllSubjTextArea.append(cleanedText);
            evalForAllSubjTextArea.setCaretPosition(0);
            teacherNameText.setText(TextFilePreProcess.getTeacherName());
            subjectComboBox.removeAllItems();
            String[] subjects = TextFilePreProcess.getSubjects();
            for(String subject : subjects){
                subjectComboBox.addItem(subject);
            }
            getSentimentButton.setEnabled(false);
            evalForOneSubjTextArea.setText("");
            subjectComboBox.setSelectedIndex(0);
            filenameTextField.setText(file.getAbsolutePath());
        } else {
            System.out.print("Open command cancelled by user." + "\n");
        }
    }//GEN-LAST:event_chooseFileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    private void write(String string){
        
        System.out.println(string);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileBtn;
    private javax.swing.JLabel evalForAllSubjLabel;
    private javax.swing.JTextArea evalForAllSubjTextArea;
    private javax.swing.JTextArea evalForOneSubjTextArea;
    private javax.swing.JTextField filenameTextField;
    private javax.swing.JButton getSentimentButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField negativeScoreTextField;
    private javax.swing.JTextArea negativeStatementsTextArea;
    private javax.swing.JButton openMulitpleFileAnalysisWindow;
    private javax.swing.JButton outputIntoCSVButton;
    private javax.swing.JButton outputIntoTextButton;
    private javax.swing.JTextField positiveScoreTextField;
    private javax.swing.JTextArea positiveStatementsTextArea;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel teacherNameLabel;
    private javax.swing.JTextField teacherNameText;
    // End of variables declaration//GEN-END:variables
}
